jokes:
  categories-url: https://api.chucknorris.io/jokes/categories
  random-joke-url: https://api.chucknorris.io/jokes/random?category={category}

keycloak:
  auth-server-url: https://auth.hama.digital/auth
  realm: demo-realm
  resource: sovtech
  public-client:  true
